# Put this file at ~/.tmux.conf

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

set -g set-clipboard on

# lets applications inside tmux access the system clipboard without tmux 
# intercepting it first
set -g allow-passthrough on

# delay before the key reaches the application inside
set -g escape-time 10

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none
