# Put this file at ~/.tmux.conf

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Enable mouse control (clickable windows, panes, resizable panes)
# Enabling this messes with copy/paste; press Fn, select, ctr-c/ctr-v
# or use mouse to select and paster
set -g mouse on

set -g set-clipboard on

# lets applications inside tmux access the system clipboard without tmux 
# intercepting it first
set -g allow-passthrough on

# delay before the key reaches the application inside
# Address vim mode switching delay (http://superuser.com/a/252717/65504)
set -g escape-time 0

# Increase scrollback buffer size from 2000 to 50000 lines
set -g history-limit 50000

# Increase tmux messages display duration from 750ms to 4s
set -g display-time 4000

# Refresh 'status-left' and 'status-right' more often, from every 15s to 5s
set -g status-interval 5

# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# Easier and faster switching between next/prev window
bind C-p previous-window
bind C-n next-window

# Upgrade $TERM
set -g default-terminal "screen-256color"

# Focus events enabled for terminals that support them
set -g focus-events on

# Super useful when using "grouped sessions" and multi-monitor setup
setw -g aggressive-resize on
